[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "SQL Database Connection Tool"
description="A tool for connecting to a SQL database that stores information about library parts stored as USDs."

# Path to the readme markdown file for.
readme  = "../../README.md"

# URL of the extension source repository.
repository = "https://github.com/Brett-Amberge/lm-db-connector"

# One of categories for UI.
category = "Database"

# Keywords for the extension
keywords = ["kit", "database", "sql", "usd"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.usd" = {}
"omni.kit.viewport.utility" = {}

# Main python module this extension provides, it will be publicly available as "import company.hello.code".
[[python.module]]
name = "lm.db.connector"

# List of additional directories with pip archives to be passed into pip using ``--find-links`` arg
# Relative paths are relative to the extension root
[python.pipapi]
archiveDirs = ["omnienv/Lib/site-packages/pip"]

# Commands to be passed to pip install before extension gets enabled
requirements = [
    "pydobc",
]

# Determines if pip will use online index if packages cannot be found locally
use_online_index = false